--DE 18 - 19
--1 
CREATE OR REPLACE TRIGGER TRS_ENROLLMENT
BEFORE INSERT OR UPDATE
ON ENROLLMENT
FOR EACH ROW
DECLARE
    SL INT;
BEGIN
    SELECT COUNT(*) INTO SL FROM ENROLLMENT WHERE STUDENTID = :NEW.STUDENTID;
    IF(SL >= 4) THEN
        DBMS_OUTPUT.PUT_LINE('LOI! KHONG HOP LE');
        ROLLBACK;
    END IF;
END;

SET SERVEROUTPUT ON
SET FEEDBACK OFF
--TEST
--STUDENT
INSERT INTO student VALUES (500,'Mr.','Fred','Crocitto','101-09 120th St.','718-555-5555','Albert Hildegard Co.','22-JAN-99','BROSENZWEIG','19-JAN-99','BROSENZW','22-JAN-99');  
--ENROLLMENT
INSERT INTO enrollment VALUES (500,98,'21-FEB-99',NULL,'DSCHERER','14-DEC-99','BROSENZW','05-JAN-00');                                                                                                 
INSERT INTO enrollment VALUES (500,99,'21-FEB-99',NULL,'DSCHERER','14-DEC-99','BROSENZW','05-JAN-00');                                                                                                  
INSERT INTO enrollment VALUES (500,101,'21-FEB-99',NULL,'DSCHERER','14-DEC-99','BROSENZW','05-JAN-00');                                                                                                 
INSERT INTO enrollment VALUES (500,102,'21-FEB-99',NULL,'DSCHERER','14-DEC-99','BROSENZW','05-JAN-00');                                                                                                  
INSERT INTO enrollment VALUES (500,100,'21-FEB-99',NULL,'DSCHERER','14-DEC-99','BROSENZW','05-JAN-00');
SELECT *  FROM ENROLLMENT WHERE STUDENTID = 500;

--2
CREATE OR REPLACE PROCEDURE PR_PRINT_LISTCOURSE(MAMH COURSE.COURSENO%TYPE)
AS
    MALOP CLASS.CLASSID%TYPE;
    DEM INT:= 0;
    CURSOR LC_CURSOR IS SELECT DISTINCT CLASSID FROM CLASS WHERE COURSENO = MAMH;
BEGIN
        OPEN LC_CURSOR;
        LOOP
        FETCH LC_CURSOR INTO MALOP;
        EXIT WHEN LC_CURSOR%NOTFOUND;
        SELECT COUNT(*) INTO DEM FROM ENROLLMENT WHERE CLASSID = MALOP;
        DBMS_OUTPUT.PUT_LINE('----- LOP: ' || MALOP || ' CO SO LUONG SINH VIEN DANG KY LA: ' || DEM);
        END LOOP;
        CLOSE LC_CURSOR;
END;

SET SERVEROUTPUT ON
EXECUTE PR_PRINT_LISTCOURSE(20);

--3
CREATE OR REPLACE FUNCTION TOTAL_COST_FOR_STUDENT (MASV ENROLLMENT.STUDENTID%TYPE)
RETURN NUMBER
AS
    SOTIEN NUMBER(9);
BEGIN
    SELECT SUM(COST) INTO SOTIEN FROM ENROLLMENT E, CLASS CS, COURSE C
    WHERE E.CLASSID = CS.CLASSID AND CS.COURSENO = C.COURSENO AND E.STUDENTID = MASV;
    RETURN SOTIEN;
END;

set serveroutput on
DECLARE
    MASV ENROLLMENT.STUDENTID%TYPE;
    SOTIEN NUMBER(9);
BEGIN
    MASV := &MASV;
    SOTIEN := TOTAL_COST_FOR_STUDENT(MASV);
    DBMS_OUTPUT.PUT_LINE('SO TIEN SINH VIEN ' || MASV || ' PHAI TRA LA: ' || SOTIEN);
END;
